//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Shape.cs
//  @ Date : 2019/8/20
//  @ Author : 
//
//

namespace SimpleFactoryPattern.Shape
{
    public abstract class Shape
    {
        public void Draw()
        {
        }
        public void Erase()
        {
        }

        public override string ToString()
        {
            return "abstract shape";
        }
    }
}


