//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Triangle.cs
//  @ Date : 2019/8/20
//  @ Author : 
//
//
namespace SimpleFactoryPattern.Shape
{
    public class Triangle : Shape
    {
        public override string ToString()
        {
            return "Shape: Triangle.";
        }
    }
}

